# Imports

## Windows test import

In [ ]:
import numpy as np
from ctypes import cdll, c_double, c_int, windll

In [ ]:
cd build/

In [ ]:
cd Release/

In [ ]:
lib = windll.LoadLibrary('Arm_kinematics.dll')

## Linux test import

In [1]:
import numpy as np
from ctypes import cdll, c_double, c_int, cdll

In [2]:
cd build/

/home/demo/dev/Reachy2_arm_kinematics/build


In [3]:
lib = cdll.LoadLibrary("libArm_kinematics.so")

# Test

In [4]:
lib.forward.restype = c_int
lib.forward.argtypes = [
    c_int, np.ctypeslib.ndpointer(dtype=np.double), c_int, 
    np.ctypeslib.ndpointer(dtype=np.double),
]

lib.inverse.restype = c_int
lib.inverse.argtypes = [
    c_int, np.ctypeslib.ndpointer(dtype=np.double), 
    np.ctypeslib.ndpointer(dtype=np.double),
]

In [5]:
lib.setup()

0

In [17]:
q = np.array((0.05, -0.26, -0.26, -1.57, 0.2, 0.15, -0.1), dtype=np.double)
M = np.zeros(16, dtype=np.double)

lib.forward(1, q, len(q), M)

1

In [18]:
np.round(M.reshape((4, 4)), 3)

array([[ 0.191, -0.194, -0.962,  0.369],
       [ 0.028,  0.981, -0.192, -0.204],
       [ 0.981,  0.01 ,  0.193, -0.305],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])

In [19]:
q2 = np.zeros(7, dtype=np.double)
lib.inverse(1, M, q2)

1

In [20]:
np.round(np.rad2deg(q2), 2)

array([  4.45, -22.44,  -7.69, -89.95,   4.82,   7.49, -13.43])

In [21]:
lib.forward(1, q2, len(q2), M)

1

In [22]:
np.round(M.reshape((4, 4)), 3)

array([[ 0.191, -0.194, -0.962,  0.369],
       [ 0.028,  0.981, -0.192, -0.204],
       [ 0.981,  0.01 ,  0.193, -0.305],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])