# Imports

## Windows test import

In [ ]:
import numpy as np
from ctypes import cdll, c_double, c_int, windll

In [ ]:
cd build/

In [ ]:
cd Debug/

In [ ]:
lib = windll.LoadLibrary('Arm_kinematics.dll')

## Linux test import

In [1]:
import numpy as np
from ctypes import cdll, c_double, c_int, cdll

In [2]:
cd build/

/home/demo/dev/Reachy2_arm_kinematics/build


In [3]:
lib = cdll.LoadLibrary("libArm_kinematics.so")

# Test

In [4]:
lib.forward.restype = c_int
lib.forward.argtypes = [
    c_int, np.ctypeslib.ndpointer(dtype=np.double), c_int, 
    np.ctypeslib.ndpointer(dtype=np.double),
]

lib.inverse.restype = c_int
lib.inverse.argtypes = [
    c_int, np.ctypeslib.ndpointer(dtype=np.double), 
    np.ctypeslib.ndpointer(dtype=np.double),
]

In [5]:
lib.setup()

0

In [6]:
q = np.array((0, -0.26, -0.26, -1.57, 0, 0, 0), dtype=np.double)
M = np.zeros(16, dtype=np.double)

lib.forward(1, q, len(q), M)

0

In [7]:
np.round(M.reshape((4, 4)), 3)

array([[-0.021, -0.001, -1.   ,  0.386],
       [ 0.082,  0.997, -0.003, -0.222],
       [ 0.996, -0.082, -0.021, -0.271],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])

In [8]:
q2 = np.zeros(7, dtype=np.double)
lib.inverse(1, M, q2)

0

In [9]:
np.round(np.rad2deg(q2), 2)

array([  1.54, -22.12,  -8.  , -89.95,  -7.36,  -0.48,  -7.35])

In [10]:
lib.forward(1, q2, len(q2), M)

0

In [11]:
np.round(M.reshape((4, 4)), 3)

array([[-0.021, -0.001, -1.   ,  0.386],
       [ 0.082,  0.997, -0.003, -0.222],
       [ 0.996, -0.082, -0.021, -0.271],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])